import { slugify } from "@/lib/slugify"

export const allProducts = [
  {
    id: 1,
    name: "1d-al-lad-100mcg-Blotter",
    slug: "1d-al-lad-100mcg-blotter",
    price: 248.99,
    image: "/americhem-product-image.png",
    description: "Lysergamides",
    inStock: true,
    rating: 4.8,
    reviews: 100,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C20H16ClN5O2",
    casNumber: "1182367-47-0",
    detailedDescription:
      "High-quality research chemical for laboratory use only. This compound is intended for research purposes and should be handled by qualified professionals in appropriate laboratory settings.",
  },
  {
    id: 2,
    name: "1P-ETH-LAD 100μg Blotters",
    slug: "1p-eth-lad-100g-blotters",
    price: 248.99,
    image: "/americhem-product-image.png",
    description: "Lysergamides",
    inStock: true,
    rating: 4.6,
    reviews: 80,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C22H27N3O2",
    casNumber: "1906382-34-2",
    detailedDescription:
      "Premium research chemical compound designed for analytical and research applications. Requires proper laboratory equipment and trained personnel for handling.",
  },
  {
    id: 3,
    name: "2-FEA Pellets 60mg",
    slug: "2-fea-pellets-60mg",
    price: 12.99,
    image: "/americhem-product-image.png",
    description: "2-FEA",
    inStock: true,
    rating: 4.7,
    reviews: 95,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-54-9",
    detailedDescription:
      "Research-grade stimulant compound for scientific investigation. Each pellet contains precisely measured amounts for consistent research applications.",
  },
  {
    id: 4,
    name: "2/3-FEA Pellets 50mg/125mg",
    slug: "2-3-fea-pellets-50mg-125mg",
    price: 20.25,
    image: "/americhem-product-image.png",
    description: "3-FEA, 2-FEA",
    inStock: true,
    rating: 4.5,
    reviews: 120,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-55-0",
    detailedDescription:
      "Combination research compound featuring both 2-FEA and 3-FEA in precisely measured pellet form for comparative studies and research applications.",
  },
  {
    id: 5,
    name: "4-HO-MET 20mg Pellets",
    slug: "4-ho-met-20mg-pellets",
    price: 24,
    image: "/americhem-product-image.png",
    description: "4-HO-MET",
    inStock: true,
    rating: 4.6,
    reviews: 75,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H18N2O2",
    casNumber: "77872-41-4",
    detailedDescription:
      "High-purity tryptamine derivative for advanced research applications. Manufactured under strict quality control standards for consistent results.",
  },
  {
    id: 6,
    name: "Buy 1B-LSD 125mcg Blotters",
    slug: "buy-1b-lsd-125mcg-blotters",
    price: 30.99,
    image: "/americhem-product-image.png",
    description: "1B-LSD",
    inStock: true,
    rating: 4.4,
    reviews: 60,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O3",
    casNumber: "1445752-09-9",
    detailedDescription:
      "Research-grade lysergamide compound on high-quality blotter paper. Designed for analytical chemistry and research purposes only.",
  },
  {
    id: 7,
    name: "Buy 1cP-AL-LAD 150mcg Blotters",
    slug: "buy-1cp-al-lad-150mcg-blotters",
    price: 46.99,
    image: "/americhem-product-image.png",
    description: "1cP-AL-LAD, AL-LAD",
    inStock: true,
    rating: 4.3,
    reviews: 85,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C22H27N3O2",
    casNumber: "2349358-81-0",
    detailedDescription:
      "Advanced lysergamide research compound featuring enhanced stability and purity. Suitable for sophisticated analytical and research applications.",
  },
  {
    id: 8,
    name: "Buy 1cP-LSD 100mcg Blotters",
    slug: "buy-1cp-lsd-100mcg-blotters",
    price: 23.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.5,
    reviews: 70,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Premium quality research chemical on professional-grade blotter substrate. Manufactured to the highest standards for reliable research outcomes.",
  },
  {
    id: 9,
    name: "Buy 1cP-LSD 10mcg Micro Pellets",
    slug: "buy-1cp-lsd-10mcg-micro-pellets",
    price: 9.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.7,
    reviews: 45,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Micro-dosed research compound for precise analytical applications. Each pellet contains accurately measured amounts for consistent research protocols.",
  },
  {
    id: 10,
    name: "Buy 1cP-LSD 150mcg Art Blotters",
    slug: "buy-1cp-lsd-150mcg-art-blotters",
    price: 25.0,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.6,
    reviews: 90,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Premium art blotter featuring high-quality research compound. Designed for analytical chemistry with enhanced visual identification markers.",
  },
  {
    id: 11,
    name: "Buy 1cP-LSD 150mcg Pellets",
    slug: "buy-1cp-lsd-150mcg-pellets",
    price: 32.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.8,
    reviews: 65,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "High-concentration research pellets for advanced analytical studies. Manufactured under strict quality control for consistent research outcomes.",
  },
  {
    id: 12,
    name: "Buy 1cP-LSD 20mcg Micro Blotters",
    slug: "buy-1cp-lsd-20mcg-micro-blotters",
    price: 30.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.5,
    reviews: 110,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Micro-dosed blotter for precise research applications. Ideal for analytical chemistry requiring exact dosage measurements.",
  },
  {
    id: 13,
    name: "Buy 1cP-MiPLA 200mcg Blotters",
    slug: "buy-1cp-mipla-200mcg-blotters",
    price: 42.99,
    image: "/americhem-product-image.png",
    description: "1cP-MiPLA",
    inStock: true,
    rating: 4.4,
    reviews: 55,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C24H31N3O2",
    casNumber: "2349358-82-1",
    detailedDescription:
      "Advanced lysergamide research compound with unique structural properties. Suitable for sophisticated analytical and comparative studies.",
  },
  {
    id: 14,
    name: "Buy 1D-LSD 10mcg Micro Pellets",
    slug: "buy-1d-lsd-10mcg-micro-pellets",
    price: 13.25,
    image: "/americhem-product-image.png",
    description: "1D-LSD",
    inStock: true,
    rating: 4.7,
    reviews: 125,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C27H35N3O2",
    casNumber: "2349358-83-2",
    detailedDescription:
      "Next-generation lysergamide research compound in micro-pellet form. Designed for precision analytical applications and research protocols.",
  },
  {
    id: 15,
    name: "Buy 1D-LSD 150mcg Blotters",
    slug: "buy-1d-lsd-150mcg-blotters",
    price: 58.99,
    image: "/americhem-product-image.png",
    description: "1D-LSD",
    inStock: true,
    rating: 4.3,
    reviews: 40,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C27H35N3O2",
    casNumber: "2349358-83-2",
    detailedDescription:
      "Premium 1D-LSD research compound on high-quality blotter substrate. Features enhanced stability and purity for advanced research applications.",
  },
  {
    id: 16,
    name: "Buy 1D-LSD 225mcg Pellets",
    slug: "buy-1d-lsd-225mcg-pellets",
    price: 86.99,
    image: "/americhem-product-image.png",
    description: "1D-LSD",
    inStock: true,
    rating: 4.6,
    reviews: 80,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C27H35N3O2",
    casNumber: "2349358-83-2",
    detailedDescription:
      "High-concentration 1D-LSD pellets for advanced research applications. Manufactured to pharmaceutical standards for consistent analytical results.",
  },
  {
    id: 17,
    name: "Buy 1P-LSD 100mcg Blotters",
    slug: "buy-1p-lsd-100mcg-blotters",
    price: 24.0,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.5,
    reviews: 150,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "Classic 1P-LSD research compound on professional-grade blotter paper. Widely used in analytical chemistry and research applications.",
  },
  {
    id: 18,
    name: "Buy 1P-LSD 150mcg Art Blotters",
    slug: "buy-1p-lsd-150mcg-art-blotters",
    price: 25.99,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.4,
    reviews: 95,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "Artistic blotter design featuring high-quality 1P-LSD research compound. Combines aesthetic appeal with analytical precision.",
  },
  {
    id: 19,
    name: "Buy 1P-LSD 150mcg Pellets",
    slug: "buy-1p-lsd-150mcg-pellets",
    price: 32.99,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.6,
    reviews: 85,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "High-concentration 1P-LSD pellets for advanced research protocols. Features enhanced stability and precise dosage for analytical applications.",
  },
  {
    id: 20,
    name: "Buy 1P-LSD 20mcg Micro Blotters",
    slug: "buy-1p-lsd-20mcg-micro-blotters",
    price: 31.99,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.3,
    reviews: 70,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "Micro-dosed 1P-LSD blotters for precision research applications. Ideal for analytical studies requiring exact dosage control.",
  },
  {
    id: 21,
    name: "Buy 1V LSD 150mcg Blotters",
    slug: "buy-1v-lsd-150mcg-blotters",
    price: 39.0,
    image: "/americhem-product-image.png",
    description: "1V-LSD Valerie",
    inStock: true,
    rating: 4.5,
    reviews: 120,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C25H31N3O3",
    casNumber: "2349358-85-4",
    detailedDescription:
      "1V-LSD (Valerie) research compound featuring unique structural modifications. Designed for comparative analytical studies and research applications.",
  },
  {
    id: 22,
    name: "Buy 1V-LSD 10mcg Micro Pellets",
    slug: "buy-1v-lsd-10mcg-micro-pellets",
    price: 10.99,
    image: "/americhem-product-image.png",
    description: "1V-LSD Valerie",
    inStock: true,
    rating: 4.4,
    reviews: 60,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C25H31N3O3",
    casNumber: "2349358-85-4",
    detailedDescription:
      "Micro-dosed 1V-LSD research pellets for precision analytical work. Ideal for studies requiring low-dose measurements.",
  },
  {
    id: 23,
    name: "Buy 1V-LSD 225mcg Art Blotters",
    slug: "buy-1v-lsd-225mcg-art-blotters",
    price: 63.0,
    image: "/americhem-product-image.png",
    description: "1V-LSD Valerie",
    inStock: true,
    rating: 4.8,
    reviews: 35,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C25H31N3O3",
    casNumber: "2349358-85-4",
    detailedDescription:
      "High-concentration 1V-LSD art blotters for advanced research. Combines aesthetic design with premium analytical quality.",
  },
  {
    id: 24,
    name: "Buy 1V-LSD 225mcg Pellets",
    slug: "buy-1v-lsd-225mcg-pellets",
    price: 63.0,
    image: "/americhem-product-image.png",
    description: "1V-LSD Valerie",
    inStock: true,
    rating: 4.2,
    reviews: 90,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C25H31N3O3",
    casNumber: "2349358-85-4",
    detailedDescription:
      "Premium high-concentration 1V-LSD pellets for sophisticated research applications. Manufactured to exacting standards.",
  },
  {
    id: 25,
    name: "Buy 2-CMC Crystal Chunks",
    slug: "buy-2-cmc-crystal-chunks",
    price: 29.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-CMC, 3-CMC, 3-MMC, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.3,
    reviews: 45,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO",
    casNumber: "1225843-86-0",
    detailedDescription:
      "High-purity 2-CMC crystals for research applications. Features excellent stability and consistent analytical properties.",
  },
  {
    id: 26,
    name: "Buy 2-CMC Crystal Powder",
    slug: "buy-2-cmc-crystal-powder",
    price: 30.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-CMC, 3-CMC, 3-MMC, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.4,
    reviews: 200,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO",
    casNumber: "1225843-86-0",
    detailedDescription:
      "Fine crystalline powder form of 2-CMC for precise research measurements. Manufactured to pharmaceutical standards.",
  },
  {
    id: 27,
    name: "Buy 2-FA Pellets 60mg",
    slug: "buy-2-fa-pellets-60mg",
    price: 5.99,
    image: "/americhem-product-image.png",
    description: "2-FA",
    inStock: true,
    rating: 4.3,
    reviews: 110,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C8H10FN",
    casNumber: "1716-60-5",
    detailedDescription:
      "Research-grade 2-FA pellets with precise dosing for analytical applications. Features enhanced stability for reliable results.",
  },
  {
    id: 28,
    name: "Buy 2-FA Powder",
    slug: "buy-2-fa-powder",
    price: 27.99,
    image: "/americhem-product-image.png",
    description: "2-FA",
    inStock: true,
    rating: 4.5,
    reviews: 85,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C8H10FN",
    casNumber: "1716-60-5",
    detailedDescription:
      "High-purity 2-FA powder for advanced research protocols. Suitable for quantitative analytical studies.",
  },
  {
    id: 29,
    name: "Buy 2-FEA Powder",
    slug: "buy-2-fea-powder",
    price: 58.99,
    image: "/americhem-product-image.png",
    description: "2-FEA",
    inStock: true,
    rating: 4.1,
    reviews: 65,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-54-9",
    detailedDescription:
      "Premium 2-FEA powder for sophisticated analytical research. Manufactured under strict quality control standards.",
  },
  {
    id: 30,
    name: "Buy 2-FMA Capsules 50mg",
    slug: "buy-2-fma-capsules-50mg",
    price: 12.99,
    image: "/americhem-product-image.png",
    description: "2-FMA",
    inStock: true,
    rating: 4.2,
    reviews: 30,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Capsules",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "1017176-48-5",
    detailedDescription:
      "Convenient 2-FMA capsules for research applications. Each capsule contains precisely measured amounts.",
  },
  {
    id: 31,
    name: "Buy 2-FMA Pellets 50mg",
    slug: "buy-2-fma-pellets-50mg",
    price: 11.25,
    image: "/americhem-product-image.png",
    description: "2-FMA",
    inStock: true,
    rating: 4.6,
    reviews: 250,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "1017176-48-5",
    detailedDescription:
      "Precision-dosed 2-FMA pellets for consistent research outcomes. Popular choice for analytical studies.",
  },
  {
    id: 32,
    name: "Buy 2-FMA Powder",
    slug: "buy-2-fma-powder",
    price: 15.0,
    image: "/americhem-product-image.png",
    description: "2-FMA",
    inStock: true,
    rating: 4.4,
    reviews: 180,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "1017176-48-5",
    detailedDescription:
      "High-quality 2-FMA powder for flexible research applications. Suitable for various analytical methodologies.",
  },
  {
    id: 33,
    name: "Buy 2-METHYL-AP-237 HCl Pellets 20mg",
    slug: "buy-2-methyl-ap-237-hcl-pellets-20mg",
    price: 11.99,
    image: "/americhem-product-image.png",
    description: "2-METHYL-AP-237 HCl",
    inStock: true,
    rating: 4.3,
    reviews: 140,
    category: "Research Chemicals",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C21H26N2O2",
    casNumber: "2503427-31-8",
    detailedDescription:
      "Research-grade 2-METHYL-AP-237 HCl pellets for advanced analytical applications. Manufactured to high purity standards.",
  },
  {
    id: 34,
    name: "Buy 2-METHYL-AP-237 HCl Powder",
    slug: "buy-2-methyl-ap-237-hcl-powder",
    price: 70.99,
    image: "/americhem-product-image.png",
    description: "2-METHYL-AP-237 HCl",
    inStock: true,
    rating: 4.5,
    reviews: 160,
    category: "Research Chemicals",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C21H26N2O2",
    casNumber: "2503427-31-8",
    detailedDescription:
      "Premium 2-METHYL-AP-237 HCl powder for sophisticated research protocols. Features excellent solubility and stability.",
  },
  {
    id: 35,
    name: "Buy 2-MMC capsules 220mg",
    slug: "buy-2-mmc-capsules-220mg",
    price: 20.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-MMC (Meow), 3-CMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.2,
    reviews: 95,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Capsules",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "Convenient 2-MMC capsules for research applications. Each capsule contains precisely measured amounts for consistent studies.",
  },
  {
    id: 36,
    name: "Buy 2-MMC crystal chunks",
    slug: "buy-2-mmc-crystal-chunks",
    price: 20.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-MMC (Meow), 3-CMC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.4,
    reviews: 75,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "High-purity 2-MMC crystal chunks for research applications. Features excellent stability and analytical properties.",
  },
  {
    id: 37,
    name: "Buy 2-MMC Crystal Powder",
    slug: "buy-2-mmc-crystal-powder",
    price: 19.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-MMC (Meow), 3-CMC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.3,
    reviews: 60,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "Fine crystalline 2-MMC powder for precise research measurements. Suitable for various analytical methodologies.",
  },
  {
    id: 38,
    name: "Buy 2-MMC Pellets 180mg",
    slug: "buy-2-mmc-pellets-180mg",
    price: 13.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-MMC (Meow), 3-CMC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.5,
    reviews: 120,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "Precision-dosed 2-MMC pellets at 180mg for consistent research applications. Manufactured to pharmaceutical standards.",
  },
  {
    id: 39,
    name: "Buy 2-MMC Pellets 220mg",
    slug: "buy-2-mmc-pellets-220mg",
    price: 15.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-MMC (Meow), 3-CMC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.4,
    reviews: 85,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "Higher concentration 2-MMC pellets at 220mg for advanced research protocols. Features excellent stability.",
  },
  {
    id: 40,
    name: "Buy 2-MMC Pellets 250mg",
    slug: "buy-2-mmc-pellets-250mg",
    price: 18.99,
    image: "/americhem-product-image.png",
    description: "2-MMC (Meow), 3-CMC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.2,
    reviews: 55,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "Maximum concentration 2-MMC pellets at 250mg for intensive research studies. Precision-manufactured for consistency.",
  },
  {
    id: 41,
    name: "Buy 2-MMC Powder",
    slug: "buy-2-mmc-powder",
    price: 18.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 2-MMC (Meow), 3-CMC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.3,
    reviews: 70,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1246911-71-6",
    detailedDescription:
      "High-quality 2-MMC powder for flexible research applications. Suitable for various analytical techniques.",
  },
  {
    id: 42,
    name: "Buy 2/3-FEA Pellets 40mg/120mg",
    slug: "buy-2-3-fea-pellets-40mg-120mg",
    price: 20.99,
    image: "/americhem-product-image.png",
    description: "3-FEA, 2-FEA",
    inStock: true,
    rating: 4.8,
    reviews: 25,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-55-0",
    detailedDescription:
      "Combination 2-FEA and 3-FEA pellets for comparative research studies. Precisely formulated for analytical applications.",
  },
  {
    id: 43,
    name: "Buy 2C-B-FLY 10mg Blister",
    slug: "buy-2c-b-fly-10mg-blister",
    price: 49.99,
    image: "/americhem-product-image.png",
    description: "2C-B-FLY",
    inStock: true,
    rating: 4.1,
    reviews: 20,
    category: "Phenethylamines",
    purity: "≥ 98%",
    form: "Blister",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16BrNO2",
    casNumber: "178557-21-6",
    detailedDescription:
      "Research-grade 2C-B-FLY in convenient blister packaging. Designed for precise dosing in analytical studies.",
  },
  {
    id: 44,
    name: "Buy 2C-B-FLY Pellets 10mg",
    slug: "buy-2c-b-fly-pellets-10mg",
    price: 6.0,
    image: "/americhem-product-image.png",
    description: "2C-B-FLY, DOC",
    inStock: true,
    rating: 4.3,
    reviews: 40,
    category: "Phenethylamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16BrNO2",
    casNumber: "178557-21-6",
    detailedDescription:
      "Precision-dosed 2C-B-FLY pellets for consistent research outcomes. Manufactured to high purity standards.",
  },
  {
    id: 45,
    name: "Buy 2C-C Pellets 30mg",
    slug: "buy-2c-c-pellets-30mg",
    price: 12.99,
    image: "/americhem-product-image.png",
    description: "2C-C, DOC",
    inStock: true,
    rating: 4.2,
    reviews: 15,
    category: "Phenethylamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H14ClNO2",
    casNumber: "88441-12-5",
    detailedDescription:
      "High-purity 2C-C pellets for phenethylamine research. Features excellent stability for analytical applications.",
  },
  {
    id: 46,
    name: "Buy 2C-D Pellets 25mg",
    slug: "buy-2c-d-pellets-25mg",
    price: 7.99,
    image: "/americhem-product-image.png",
    description: "2C-D, DOC",
    inStock: true,
    rating: 4.6,
    reviews: 35,
    category: "Phenethylamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H19NO2",
    casNumber: "88441-11-4",
    detailedDescription:
      "Research-grade 2C-D pellets for phenethylamine studies. Precisely measured for consistent analytical results.",
  },
  {
    id: 47,
    name: "Buy 2F-Ketamine Crystal Chunks",
    slug: "buy-2f-ketamine-crystal-chunks",
    price: 9.99,
    image: "/americhem-product-image.png",
    description: "2F-Ketamine (2-FDCK), 3-MeO-PCP",
    inStock: true,
    rating: 4.7,
    reviews: 12,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16ClFNO",
    casNumber: "111982-49-1",
    detailedDescription:
      "High-purity 2F-Ketamine crystal chunks for dissociative research. Features excellent analytical properties.",
  },
  {
    id: 48,
    name: "Buy 2F-Ketamine Crystal powder",
    slug: "buy-2f-ketamine-crystal-powder",
    price: 9.99,
    image: "/americhem-product-image.png",
    description: "2F-Ketamine (2-FDCK), 3-MeO-PCP",
    inStock: true,
    rating: 4.5,
    reviews: 8,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16ClFNO",
    casNumber: "111982-49-1",
    detailedDescription:
      "Fine crystalline 2F-Ketamine powder for precise research measurements. Suitable for various analytical methods.",
  },
  {
    id: 49,
    name: "Buy 2F-Ketamine Pellets – 100mg",
    slug: "buy-2f-ketamine-pellets-100mg",
    price: 18.99,
    image: "/americhem-product-image.png",
    description: "2F-Ketamine (2-FDCK), 3-MeO-PCP",
    inStock: true,
    rating: 4.4,
    reviews: 300,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16ClFNO",
    casNumber: "111982-49-1",
    detailedDescription:
      "Standard 100mg 2F-Ketamine pellets for dissociative research. Popular choice for analytical applications.",
  },
  {
    id: 50,
    name: "Buy 2F-Ketamine Pellets – 50mg",
    slug: "buy-2f-ketamine-pellets-50mg",
    price: 13.0,
    image: "/americhem-product-image.png",
    description: "2F-Ketamine (2-FDCK), 3-MeO-PCP",
    inStock: true,
    rating: 4.3,
    reviews: 90,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16ClFNO",
    casNumber: "111982-49-1",
    detailedDescription:
      "Lower dose 50mg 2F-Ketamine pellets for precise research applications. Manufactured to pharmaceutical standards.",
  },
  {
    id: 51,
    name: "Buy 2F-Ketamine Spray – 15%",
    slug: "buy-2f-ketamine-spray-15",
    price: 249.99,
    image: "/americhem-product-image.png",
    description: "2F-Ketamine (2-FDCK), 3-MeO-PCP",
    inStock: true,
    rating: 4.5,
    reviews: 220,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Spray",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16ClFNO",
    casNumber: "111982-49-1",
    detailedDescription:
      "2F-Ketamine spray solution at 15% concentration for advanced research applications. Features precise dosing mechanism.",
  },
  {
    id: 52,
    name: "Buy 2F-Ketamine Spray – 25%",
    slug: "buy-2f-ketamine-spray-25",
    price: 250,
    image: "/americhem-product-image.png",
    description: "2F-Ketamine (2-FDCK), 3-MeO-PCP",
    inStock: true,
    rating: 4.2,
    reviews: 180,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Spray",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H16ClFNO",
    casNumber: "111982-49-1",
    detailedDescription:
      "High-concentration 2F-Ketamine spray at 25% for intensive research studies. Premium formulation for analytical work.",
  },
  {
    id: 53,
    name: "Buy 3-CEC Crystal",
    slug: "buy-3-cec-crystal",
    price: 24.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-CEC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.1,
    reviews: 65,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H14ClNO",
    casNumber: "777666-01-2",
    detailedDescription:
      "High-purity 3-CEC crystals for stimulant research. Features excellent analytical characteristics.",
  },
  {
    id: 54,
    name: "Buy 3-CL-PCP Crystal",
    slug: "buy-3-cl-pcp-crystal",
    price: 37,
    image: "/americhem-product-image.png",
    description: "3-CL-PCP, 3-MeO-PCP",
    inStock: true,
    rating: 4.4,
    reviews: 45,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H24ClN",
    casNumber: "134111-55-6",
    detailedDescription:
      "Research-grade 3-CL-PCP crystals for dissociative compound studies. Manufactured to high purity standards.",
  },
  {
    id: 55,
    name: "Buy 3-FA Pellets 50mg",
    slug: "buy-3-fa-pellets-50mg",
    price: 25,
    image: "/americhem-product-image.png",
    description: "3-FA",
    inStock: true,
    rating: 4.6,
    reviews: 55,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C8H10FN",
    casNumber: "1346604-45-4",
    detailedDescription:
      "Precision-dosed 3-FA pellets for fluoroamphetamine research. Features consistent analytical properties.",
  },
  {
    id: 56,
    name: "Buy 3-FA Powder",
    slug: "buy-3-fa-powder",
    price: 25,
    image: "/americhem-product-image.png",
    description: "3-FA",
    inStock: true,
    rating: 4.3,
    reviews: 25,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C8H10FN",
    casNumber: "1346604-45-4",
    detailedDescription:
      "High-purity 3-FA powder for flexible research applications. Suitable for various analytical methodologies.",
  },
  {
    id: 57,
    name: "Buy 3-FEA Pellets 150mg",
    slug: "buy-3-fea-pellets-150mg",
    price: 19,
    image: "/americhem-product-image.png",
    description: "3-FEA",
    inStock: true,
    rating: 4.2,
    reviews: 40,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-55-0",
    detailedDescription:
      "High-concentration 3-FEA pellets for stimulant research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 58,
    name: "Buy 3-FEA Powder",
    slug: "buy-3-fea-powder",
    price: 25,
    image: "/americhem-product-image.png",
    description: "3-FEA",
    inStock: true,
    rating: 4.5,
    reviews: 18,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-55-0",
    detailedDescription:
      "Premium 3-FEA powder for advanced analytical applications. Features excellent solubility and stability.",
  },
  {
    id: 59,
    name: "Buy 3-FMA Pellets 50mg",
    slug: "buy-3-fma-pellets-50mg",
    price: 11,
    image: "/americhem-product-image.png",
    description: "3-FMA",
    inStock: true,
    rating: 4.4,
    reviews: 30,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "1346594-09-7",
    detailedDescription:
      "Research-grade 3-FMA pellets for fluoromethamphetamine studies. Precisely dosed for consistent results.",
  },
  {
    id: 60,
    name: "Buy 3-FMA Powder",
    slug: "buy-3-fma-powder",
    price: 21.89,
    image: "/americhem-product-image.png",
    description: "3-FMA",
    inStock: true,
    rating: 4.7,
    reviews: 12,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "1346594-09-7",
    detailedDescription:
      "High-quality 3-FMA powder for flexible research applications. Suitable for various analytical techniques.",
  },
  {
    id: 61,
    name: "Buy 3-FMC Powder",
    slug: "buy-3-fmc-powder",
    price: 10,
    image: "/americhem-product-image.png",
    description: "3-FMC",
    inStock: true,
    rating: 4.6,
    reviews: 15,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1225617-76-2",
    detailedDescription:
      "Research-grade 3-FMC powder for fluoromethcathinone studies. Features excellent analytical properties.",
  },
  {
    id: 62,
    name: "Buy 3-FPM Pellets 60mg",
    slug: "buy-3-fpm-pellets-60mg",
    price: 10.25,
    image: "/americhem-product-image.png",
    description: "3-FPM",
    inStock: true,
    rating: 4.5,
    reviews: 10,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FN",
    casNumber: "1803562-83-5",
    detailedDescription:
      "Precision-dosed 3-FPM pellets for phenmetrazine research. Manufactured to high purity standards.",
  },
  {
    id: 63,
    name: "Buy 3-FPM Powder",
    slug: "buy-3-fpm-powder",
    price: 26.99,
    image: "/americhem-product-image.png",
    description: "3-FPM",
    inStock: true,
    rating: 4.8,
    reviews: 6,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FN",
    casNumber: "1803562-83-5",
    detailedDescription:
      "Premium 3-FPM powder for advanced analytical applications. Features excellent stability for research.",
  },
  {
    id: 64,
    name: "Buy 3-HO-PCE Powder",
    slug: "buy-3-ho-pce-powder",
    price: 70.99,
    image: "/americhem-product-image.png",
    description: "3-HO-PCE, 3-MeO-PCP",
    inStock: true,
    rating: 4.7,
    reviews: 8,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H25NO",
    casNumber: "79295-51-1",
    detailedDescription:
      "High-purity 3-HO-PCE powder for dissociative arylcyclohexylamine research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 65,
    name: "Buy 3-HO-PCP Powder",
    slug: "buy-3-ho-pcp-powder",
    price: 40.99,
    image: "/americhem-product-image.png",
    description: "3-HO-PCP, 3-MeO-PCP",
    inStock: true,
    rating: 4.4,
    reviews: 22,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H25NO",
    casNumber: "79295-48-6",
    detailedDescription:
      "Research-grade 3-HO-PCP powder for advanced dissociative studies. Features excellent analytical characteristics.",
  },
  {
    id: 66,
    name: "Buy 3-Me-PCE Powder",
    slug: "buy-3-me-pce-powder",
    price: 71.0,
    image: "/americhem-product-image.png",
    description: "3-Me-PCE, 3-MeO-PCP",
    inStock: true,
    rating: 4.9,
    reviews: 3,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C18H27N",
    casNumber: "2201-45-6",
    detailedDescription:
      "Premium 3-Me-PCE powder for sophisticated dissociative research. Manufactured to the highest purity standards.",
  },
  {
    id: 67,
    name: "Buy 3-Me-PCP Powder",
    slug: "buy-3-me-pcp-powder",
    price: 71.0,
    image: "/americhem-product-image.png",
    description: "3-MeO-PCP, 3-Me-PCP",
    inStock: true,
    rating: 4.8,
    reviews: 7,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C18H27N",
    casNumber: "2201-46-7",
    detailedDescription:
      "High-quality 3-Me-PCP powder for arylcyclohexylamine research. Features excellent stability and purity.",
  },
  {
    id: 68,
    name: "Buy 3-Me-PCPy Powder",
    slug: "buy-3-me-pcpy-powder",
    price: 60.0,
    image: "/americhem-product-image.png",
    description: "3-MeO-PCP, 3-Me-PCPy",
    inStock: true,
    rating: 4.6,
    reviews: 9,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C19H29N",
    casNumber: "2201-47-8",
    detailedDescription:
      "Research-grade 3-Me-PCPy powder for advanced dissociative studies. Manufactured under strict quality control.",
  },
  {
    id: 69,
    name: "Buy 3-MEC Powder",
    slug: "buy-3-mec-powder",
    price: 13.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MEC, 3-MMC, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.7,
    reviews: 11,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H17NO",
    casNumber: "1225617-77-3",
    detailedDescription:
      "High-purity 3-MEC powder for ethylcathinone research. Features excellent analytical properties.",
  },
  {
    id: 70,
    name: "Buy 3-MeO-PCE Powder",
    slug: "buy-3-meo-pce-powder",
    price: 60.0,
    image: "/americhem-product-image.png",
    description: "3-MeO-PCE, 3-MeO-PCP",
    inStock: true,
    rating: 4.8,
    reviews: 5,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C18H27NO",
    casNumber: "2201-48-9",
    detailedDescription:
      "Premium 3-MeO-PCE powder for advanced arylcyclohexylamine research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 71,
    name: "Buy 3-MMA Crystal",
    slug: "buy-3-mma-crystal",
    price: 45.0,
    image: "/americhem-product-image.png",
    description: "3-MMA",
    inStock: true,
    rating: 4.9,
    reviews: 4,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H15N",
    casNumber: "1082-88-8",
    detailedDescription:
      "High-purity 3-MMA crystals for methylamphetamine research. Features excellent analytical characteristics.",
  },
  {
    id: 72,
    name: "Buy 3-MMA Powder",
    slug: "buy-3-mma-powder",
    price: 50.0,
    image: "/americhem-product-image.png",
    description: "3-MMA",
    inStock: true,
    rating: 4.9,
    reviews: 2,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H15N",
    casNumber: "1082-88-8",
    detailedDescription:
      "Premium 3-MMA powder for advanced stimulant research. Manufactured to the highest purity standards.",
  },
  {
    id: 73,
    name: "Buy 3F-a-PVP Crystal",
    slug: "buy-3f-a-pvp-crystal",
    price: 24.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, 3F-a-PVP, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.7,
    reviews: 6,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H20FNO",
    casNumber: "2732926-24-6",
    detailedDescription:
      "Research-grade 3F-a-PVP crystals for pyrrolidinophenone studies. Features excellent stability.",
  },
  {
    id: 74,
    name: "Buy 3F-PCP Crystal",
    slug: "buy-3f-pcp-crystal",
    price: 50.0,
    image: "/americhem-product-image.png",
    description: "3F-PCP (3-FLUORO-PCP), 3-MeO-PCP",
    inStock: true,
    rating: 4.8,
    reviews: 3,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H24FN",
    casNumber: "82692-93-1",
    detailedDescription:
      "High-purity 3F-PCP crystals for fluorophencyclidine research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 75,
    name: "Buy 4-AcO-DET Powder",
    slug: "buy-4-aco-det-powder",
    price: 70.25,
    image: "/americhem-product-image.png",
    description: "4-AcO-DET",
    inStock: true,
    rating: 4.8,
    reviews: 4,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H22N2O2",
    casNumber: "1163-70-2",
    detailedDescription:
      "Premium 4-AcO-DET powder for tryptamine research. Features excellent analytical properties.",
  },
  {
    id: 76,
    name: "Buy 4-AcO-MET 20mg Pellets",
    slug: "buy-4-aco-met-20mg-pellets",
    price: 25.99,
    image: "/americhem-product-image.png",
    description: "4-AcO-MET",
    inStock: true,
    rating: 4.9,
    reviews: 2,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H20N2O2",
    casNumber: "250-28-2",
    detailedDescription:
      "Precision-dosed 4-AcO-MET pellets for advanced tryptamine research. Manufactured to high purity standards.",
  },
  {
    id: 77,
    name: "Buy 4-AcO-MET Powder",
    slug: "buy-4-aco-met-powder",
    price: 80.0,
    image: "/americhem-product-image.png",
    description: "4-AcO-MET",
    inStock: true,
    rating: 4.7,
    reviews: 5,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H20N2O2",
    casNumber: "250-28-2",
    detailedDescription:
      "High-quality 4-AcO-MET powder for flexible research applications. Suitable for various analytical methodologies.",
  },
  {
    id: 78,
    name: "Buy 4-BMC Crystals",
    slug: "buy-4-bmc-crystals",
    price: 14.25,
    image: "/americhem-product-image.png",
    description: "4-BMC",
    inStock: true,
    rating: 4.9,
    reviews: 1,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13BrNO",
    casNumber: "38235-95-5",
    detailedDescription:
      "Research-grade 4-BMC crystals for bromomethcathinone studies. Features excellent analytical properties.",
  },
  {
    id: 79,
    name: "Buy 4-CL-PVP Crystals",
    slug: "buy-4-cl-pvp-crystals",
    price: 25.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, 4-CL-PVP, a-PHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.8,
    reviews: 3,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H20ClNO",
    casNumber: "82822-14-8",
    detailedDescription:
      "High-purity 4-CL-PVP crystals for chloropyrrolidinophenone research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 80,
    name: "Buy 4-FMA Capsules 130mg",
    slug: "buy-4-fma-capsules-130mg",
    price: 20.0,
    image: "/americhem-product-image.png",
    description: "4-FMA",
    inStock: true,
    rating: 5.0,
    reviews: 1,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Capsules",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "351-03-1",
    detailedDescription:
      "Convenient 4-FMA capsules for fluoromethamphetamine research. Precisely measured for consistent studies.",
  },
  {
    id: 81,
    name: "Buy 4-FMA Pellets 100mg",
    slug: "buy-4-fma-pellets-100mg",
    price: 3.0,
    image: "/americhem-product-image.png",
    description: "4-FMA",
    inStock: true,
    rating: 4.9,
    reviews: 2,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "351-03-1",
    detailedDescription:
      "Standard 4-FMA pellets at 100mg for research applications. Features excellent stability.",
  },
  {
    id: 82,
    name: "Buy 4-FMA Pellets 150mg",
    slug: "buy-4-fma-pellets-150mg",
    price: 17.0,
    image: "/americhem-product-image.png",
    description: "4-FMA",
    inStock: true,
    rating: 4.8,
    reviews: 7,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "351-03-1",
    detailedDescription:
      "Higher concentration 4-FMA pellets at 150mg for advanced research. Manufactured to high purity standards.",
  },
  {
    id: 83,
    name: "Buy 4-FMA Powder",
    slug: "buy-4-fma-powder",
    price: 14.0,
    image: "/americhem-product-image.png",
    description: "4-FMA",
    inStock: true,
    rating: 4.8,
    reviews: 9,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C9H12FN",
    casNumber: "351-03-1",
    detailedDescription:
      "High-quality 4-FMA powder for flexible research applications. Suitable for various analytical techniques.",
  },
  {
    id: 84,
    name: "Buy 4-HO-MiPT 20mg Pellets",
    slug: "buy-4-ho-mipt-20mg-pellets",
    price: 25.0,
    image: "/americhem-product-image.png",
    description: "4-HO-MiPT",
    inStock: true,
    rating: 4.9,
    reviews: 4,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H22N2O",
    casNumber: "77872-43-6",
    detailedDescription:
      "Precision-dosed 4-HO-MiPT pellets for tryptamine research. Features excellent analytical characteristics.",
  },
  {
    id: 85,
    name: "Buy 4-MPD Crystals",
    slug: "buy-4-mpd-crystals",
    price: 18.0,
    image: "/americhem-product-image.png",
    description: "4-MPD",
    inStock: true,
    rating: 4.5,
    reviews: 18,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C14H19NO2",
    casNumber: "1487-14-9",
    detailedDescription:
      "Research-grade 4-MPD crystals for methylphenidate research. Manufactured under strict quality control.",
  },
  {
    id: 86,
    name: "Buy 4B-MAR Powder",
    slug: "buy-4b-mar-powder",
    price: 65.0,
    image: "/americhem-product-image.png",
    description: "4-MAR ICE Analogues",
    inStock: true,
    rating: 4.4,
    reviews: 22,
    category: "Research Chemicals",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H14BrNO",
    casNumber: "82821-92-9",
    detailedDescription:
      "High-purity 4B-MAR powder for aminorex analogue research. Features excellent stability.",
  },
  {
    id: 87,
    name: "Buy 4C-MAR Powder",
    slug: "buy-4c-mar-powder",
    price: 35.0,
    image: "/americhem-product-image.png",
    description: "4-MAR ICE Analogues",
    inStock: true,
    rating: 4.6,
    reviews: 12,
    category: "Research Chemicals",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H14ClNO",
    casNumber: "82821-93-0",
    detailedDescription:
      "Research-grade 4C-MAR powder for chlorinated aminorex studies. Manufactured to pharmaceutical standards.",
  },
  {
    id: 88,
    name: "Buy 4F-MAR Powder",
    slug: "buy-4f-mar-powder",
    price: 34.99,
    image: "/americhem-product-image.png",
    description: "4-MAR ICE Analogues",
    inStock: true,
    rating: 4.8,
    reviews: 6,
    category: "Research Chemicals",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H14FNO",
    casNumber: "82821-94-1",
    detailedDescription:
      "Premium 4F-MAR powder for fluorinated aminorex research. Features excellent analytical properties.",
  },
  {
    id: 89,
    name: "Buy 4F-MPH 15mg Pellets",
    slug: "buy-4f-mph-15mg-pellets",
    price: 2.5,
    image: "/americhem-product-image.png",
    description: "4F-methylphenidate (4F-MPH)",
    inStock: true,
    rating: 4.5,
    reviews: 14,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C14H18FNO2",
    casNumber: "1354631-78-7",
    detailedDescription:
      "Low-dose 4F-MPH pellets for fluoromethylphenidate research. Precisely measured for analytical applications.",
  },
  {
    id: 90,
    name: "Buy 4F-MPH 25mg Pellets",
    slug: "buy-4f-mph-25mg-pellets",
    price: 43.0,
    image: "/americhem-product-image.png",
    description: "4F-methylphenidate (4F-MPH)",
    inStock: true,
    rating: 4.3,
    reviews: 8,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C14H18FNO2",
    casNumber: "1354631-78-7",
    detailedDescription:
      "Standard 25mg 4F-MPH pellets for research applications. Manufactured to high purity standards.",
  },
  {
    id: 91,
    name: "Buy 4F-MPH 30mg Pellets",
    slug: "buy-4f-mph-30mg-pellets",
    price: 47.99,
    image: "/americhem-product-image.png",
    description: "4F-methylphenidate (4F-MPH)",
    inStock: true,
    rating: 4.4,
    reviews: 25,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C14H18FNO2",
    casNumber: "1354631-78-7",
    detailedDescription:
      "Higher concentration 4F-MPH pellets at 30mg for intensive research. Features excellent stability.",
  },
  {
    id: 92,
    name: "Buy 4F-MPH Powder",
    slug: "buy-4f-mph-powder",
    price: 12.25,
    image: "/americhem-product-image.png",
    description: "4F-methylphenidate (4F-MPH)",
    inStock: true,
    rating: 4.6,
    reviews: 150,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C14H18FNO2",
    casNumber: "1354631-78-7",
    detailedDescription:
      "High-quality 4F-MPH powder for flexible research applications. Popular choice for analytical studies.",
  },
  {
    id: 93,
    name: "Buy 4f-Pihp Powder",
    slug: "buy-4f-pihp-powder",
    price: 20.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, a-PHP, a-PiHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.7,
    reviews: 20,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H22FNO",
    casNumber: "2732926-26-8",
    detailedDescription:
      "Research-grade 4f-Pihp powder for pyrrolidinophenone research. Features excellent analytical characteristics.",
  },
  {
    id: 94,
    name: "Buy 5-APB Capsules 90mg",
    slug: "buy-5-apb-capsules-90mg",
    price: 31.5,
    image: "/americhem-product-image.png",
    description: "5-APB (Benzo)",
    inStock: true,
    rating: 4.8,
    reviews: 95,
    category: "Empathogens",
    purity: "≥ 98%",
    form: "Capsules",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO",
    casNumber: "286834-85-3",
    detailedDescription:
      "Convenient 5-APB capsules for benzofuran research. Each capsule precisely measured for consistent studies.",
  },
  {
    id: 95,
    name: "Buy 5-APB Powder",
    slug: "buy-5-apb-powder",
    price: 27.0,
    image: "/americhem-product-image.png",
    description: "5-APB (Benzo)",
    inStock: true,
    rating: 4.5,
    reviews: 80,
    category: "Empathogens",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO",
    casNumber: "286834-85-3",
    detailedDescription:
      "High-purity 5-APB powder for flexible empathogen research. Suitable for various analytical methodologies.",
  },
  {
    id: 96,
    name: "Buy 5-MAPB Capsules 120mg",
    slug: "buy-5-mapb-capsules-120mg",
    price: 50.0,
    image: "/americhem-product-image.png",
    description: "5-MAPB (Benzo)",
    inStock: true,
    rating: 4.7,
    reviews: 65,
    category: "Empathogens",
    purity: "≥ 98%",
    form: "Capsules",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H15NO",
    casNumber: "1354631-79-8",
    detailedDescription:
      "Premium 5-MAPB capsules for benzofuran research. Features excellent analytical properties.",
  },
  {
    id: 97,
    name: "Buy 5-MAPB Powder",
    slug: "buy-5-mapb-powder",
    price: 39.0,
    image: "/americhem-product-image.png",
    description: "5-MAPB (Benzo)",
    inStock: true,
    rating: 4.6,
    reviews: 50,
    category: "Empathogens",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C12H15NO",
    casNumber: "1354631-79-8",
    detailedDescription:
      "Research-grade 5-MAPB powder for advanced empathogen studies. Manufactured to pharmaceutical standards.",
  },
  {
    id: 98,
    name: "Buy 5-MeO-DALT 20mg Pellets",
    slug: "buy-5-meo-dalt-20mg-pellets",
    price: 25.0,
    image: "/americhem-product-image.png",
    description: "5-MeO-DALT",
    inStock: true,
    rating: 4.8,
    reviews: 30,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H24N2O",
    casNumber: "928822-98-4",
    detailedDescription:
      "Precision-dosed 5-MeO-DALT pellets for tryptamine research. Features excellent stability.",
  },
  {
    id: 99,
    name: "Buy 5-MeO-DMT Powder",
    slug: "buy-5-meo-dmt-powder",
    price: 80.0,
    image: "/americhem-product-image.png",
    description: "5-MeO-DMT",
    inStock: true,
    rating: 4.9,
    reviews: 45,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H18N2O",
    casNumber: "1019-45-0",
    detailedDescription:
      "High-purity 5-MeO-DMT powder for advanced tryptamine research. Manufactured to the highest standards.",
  },
  {
    id: 100,
    name: "Buy 5-MeO-MiPT 20mg Pellets",
    slug: "buy-5-meo-mipt-20mg-pellets",
    price: 25.0,
    image: "/americhem-product-image.png",
    description: "5-MeO-MiPT",
    inStock: true,
    rating: 4.7,
    reviews: 35,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H24N2O",
    casNumber: "96096-55-8",
    detailedDescription:
      "Research-grade 5-MeO-MiPT pellets for tryptamine studies. Precisely dosed for consistent results.",
  },
  {
    id: 101,
    name: "Buy 6-APB Capsules 120mg",
    slug: "buy-6-apb-capsules-120mg",
    price: 31.5,
    image: "/americhem-product-image.png",
    description: "6-APB (Benzo)",
    inStock: true,
    rating: 4.6,
    reviews: 70,
    category: "Empathogens",
    purity: "≥ 98%",
    form: "Capsules",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO",
    casNumber: "286834-80-8",
    detailedDescription:
      "Convenient 6-APB capsules for benzofuran research. Each capsule contains precisely measured amounts.",
  },
  {
    id: 102,
    name: "Buy 6-APB Powder",
    slug: "buy-6-apb-powder",
    price: 27.0,
    image: "/americhem-product-image.png",
    description: "6-APB (Benzo)",
    inStock: true,
    rating: 4.5,
    reviews: 85,
    category: "Empathogens",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO",
    casNumber: "286834-80-8",
    detailedDescription:
      "High-quality 6-APB powder for flexible empathogen research. Suitable for various analytical techniques.",
  },
  {
    id: 103,
    name: "Buy A-PCYP Crystals",
    slug: "buy-a-pcyp-crystals",
    price: 23.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, a-PHP, a-PiHP, A-PCYP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.4,
    reviews: 40,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H25NO",
    casNumber: "19118-08-8",
    detailedDescription:
      "Research-grade A-PCYP crystals for pyrrolidinophenone research. Features excellent analytical properties.",
  },
  {
    id: 104,
    name: "Buy a-PHP Powder",
    slug: "buy-a-php-powder",
    price: 8.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, a-PHP, a-PiHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.3,
    reviews: 55,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H21NO",
    casNumber: "13415-59-3",
    detailedDescription:
      "High-purity a-PHP powder for pyrrolidinohexanophenone research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 105,
    name: "Buy a-PiHP Crystal",
    slug: "buy-a-pihp-crystal",
    price: 18.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, a-PHP, a-PiHP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.5,
    reviews: 60,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H23NO",
    casNumber: "13415-60-6",
    detailedDescription:
      "Premium a-PiHP crystals for pyrrolidinoisohexanophenone research. Features excellent stability.",
  },
  {
    id: 106,
    name: "Buy a-PVP Crystal",
    slug: "buy-a-pvp-crystal",
    price: 12.99,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, a-PHP, a-PiHP, a-PVP, Hexedrone (Hexen)",
    inStock: true,
    rating: 4.6,
    reviews: 75,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H21NO",
    casNumber: "14530-33-7",
    detailedDescription:
      "Research-grade a-PVP crystals for pyrrolidinovalerophenone research. Manufactured under strict quality control.",
  },
  {
    id: 107,
    name: "Buy Bromazolam Pellets 2.5mg",
    slug: "buy-bromazolam-pellets-2-5mg",
    price: 4.5,
    image: "/americhem-product-image.png",
    description: "Bromazolam",
    inStock: true,
    rating: 4.8,
    reviews: 120,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H13BrN4",
    casNumber: "71368-80-4",
    detailedDescription:
      "Precision-dosed Bromazolam pellets for benzodiazepine research. Features excellent analytical characteristics.",
  },
  {
    id: 108,
    name: "Buy Clonazolam Pellets 0.5mg",
    slug: "buy-clonazolam-pellets-0-5mg",
    price: 3.5,
    image: "/americhem-product-image.png",
    description: "Clonazolam",
    inStock: true,
    rating: 4.7,
    reviews: 95,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H12ClN5",
    casNumber: "33887-02-4",
    detailedDescription:
      "High-purity Clonazolam pellets for benzodiazepine research. Precisely measured for consistent studies.",
  },
  {
    id: 109,
    name: "Buy DCK Crystal",
    slug: "buy-dck-crystal",
    price: 10.0,
    image: "/americhem-product-image.png",
    description: "DCK (Deschloroketamine), 3-MeO-PCP",
    inStock: true,
    rating: 4.6,
    reviews: 50,
    category: "Dissociatives",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H17NO",
    casNumber: "4631-27-0",
    detailedDescription:
      "Research-grade DCK crystals for deschloroketamine research. Features excellent analytical properties.",
  },
  {
    id: 110,
    name: "Buy Etizolam Pellets 1mg",
    slug: "buy-etizolam-pellets-1mg",
    price: 2.5,
    image: "/americhem-product-image.png",
    description: "Etizolam",
    inStock: true,
    rating: 4.9,
    reviews: 200,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H15ClN4S",
    casNumber: "40054-69-1",
    detailedDescription:
      "Premium Etizolam pellets for thienodiazepine research. Popular choice for analytical applications.",
  },
  {
    id: 111,
    name: "Buy Flualprazolam Pellets 1mg",
    slug: "buy-flualprazolam-pellets-1mg",
    price: 3.0,
    image: "/americhem-product-image.png",
    description: "Flualprazolam",
    inStock: true,
    rating: 4.8,
    reviews: 110,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H12ClFN4",
    casNumber: "28910-99-8",
    detailedDescription:
      "High-quality Flualprazolam pellets for fluorinated benzodiazepine research. Manufactured to high purity standards.",
  },
  {
    id: 112,
    name: "Buy Flunitrazolam Pellets 0.25mg",
    slug: "buy-flunitrazolam-pellets-0-25mg",
    price: 2.5,
    image: "/americhem-product-image.png",
    description: "Flunitrazolam",
    inStock: true,
    rating: 4.7,
    reviews: 85,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H12FN5O3",
    casNumber: "2886-65-9",
    detailedDescription:
      "Precision-dosed Flunitrazolam pellets for triazolobenzodiazepine research. Features excellent stability.",
  },
  {
    id: 113,
    name: "Buy Flubromazepam Pellets 8mg",
    slug: "buy-flubromazepam-pellets-8mg",
    price: 4.0,
    image: "/americhem-product-image.png",
    description: "Flubromazepam",
    inStock: true,
    rating: 4.6,
    reviews: 70,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C15H10BrFN2O",
    casNumber: "2647-50-9",
    detailedDescription:
      "Research-grade Flubromazepam pellets for benzodiazepine studies. Manufactured under strict quality control.",
  },
  {
    id: 114,
    name: "Buy Flubromazolam Pellets 0.25mg",
    slug: "buy-flubromazolam-pellets-0-25mg",
    price: 3.0,
    image: "/americhem-product-image.png",
    description: "Flubromazolam",
    inStock: true,
    rating: 4.8,
    reviews: 90,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C17H12BrFN4",
    casNumber: "612526-40-6",
    detailedDescription:
      "High-purity Flubromazolam pellets for triazolobenzodiazepine research. Precisely measured for analytical work.",
  },
  {
    id: 115,
    name: "Buy Mexedrone Crystal",
    slug: "buy-mexedrone-crystal",
    price: 15.0,
    image: "/americhem-product-image.png",
    description: "4-CMC, 3-MMC, a-PHP, Hexedrone (Hexen), Mexedrone",
    inStock: true,
    rating: 4.5,
    reviews: 45,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C11H13NO2",
    casNumber: "1198-86-1",
    detailedDescription:
      "Premium Mexedrone crystals for methoxetamine research. Features excellent analytical characteristics.",
  },
  {
    id: 116,
    name: "Buy N-Ethylhexedrone (NEH) Crystal",
    slug: "buy-n-ethylhexedrone-neh-crystal",
    price: 20.0,
    image: "/americhem-product-image.png",
    description: "Hexedrone (Hexen), NEH",
    inStock: true,
    rating: 4.6,
    reviews: 55,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H19NO",
    casNumber: "18016-71-8",
    detailedDescription:
      "Research-grade N-Ethylhexedrone crystals for cathinone research. Manufactured to pharmaceutical standards.",
  },
  {
    id: 117,
    name: "Buy O-DSMT Pellets 30mg",
    slug: "buy-o-dsmt-pellets-30mg",
    price: 5.5,
    image: "/americhem-product-image.png",
    description: "O-DSMT",
    inStock: true,
    rating: 4.7,
    reviews: 100,
    category: "Research Chemicals",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H25NO2",
    casNumber: "73986-53-5",
    detailedDescription:
      "High-purity O-DSMT pellets for tramadol metabolite research. Precision-dosed for analytical applications.",
  },
  {
    id: 118,
    name: "Buy O-PCE Crystal",
    slug: "buy-o-pce-crystal",
    price: 35.0,
    image: "/americhem-product-image.png",
    description: "O-PCE, 3-MeO-PCP",
    inStock: true,
    rating: 4.8,
    reviews: 35,
    category: "Dissociatives",
    purity: "≥ 98%",
    form: "Crystal",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C18H27NO",
    casNumber: "4551-92-2",
    detailedDescription:
      "Premium O-PCE crystals for arylcyclohexylamine research. Features excellent analytical properties.",
  },
  {
    id: 119,
    name: "Buy Pyrazolam Pellets 3mg",
    slug: "buy-pyrazolam-pellets-3mg",
    price: 4.0,
    image: "/americhem-product-image.png",
    description: "Pyrazolam",
    inStock: true,
    rating: 4.6,
    reviews: 75,
    category: "Benzodiazepines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C16H12BrN5",
    casNumber: "39243-02-2",
    detailedDescription:
      "Research-grade Pyrazolam pellets for triazolobenzodiazepine studies. Manufactured under strict quality control.",
  },
  {
    id: 120,
    name: "Buy SGT-151 Powder",
    slug: "buy-sgt-151-powder",
    price: 45.0,
    image: "/americhem-product-image.png",
    description: "SGT-151",
    inStock: true,
    rating: 4.5,
    reviews: 40,
    category: "Cannabinoids",
    purity: "≥ 98%",
    form: "Powder",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H21FN2O2",
    casNumber: "1099-87-2",
    detailedDescription:
      "High-purity SGT-151 powder for synthetic cannabinoid research. Features excellent stability and analytical characteristics.",
  },
]

// Generate slugs for any products that don't have one
export const productsWithSlugs = allProducts.map((product) => ({
  ...product,
  slug: product.slug || slugify(product.name),
}))
