import { slugify } from "@/lib/slugify"

export const allProducts = [
  {
    id: 1,
    name: "1d-al-lad-100mcg-Blotter",
    slug: "1d-al-lad-100mcg-blotter",
    price: 248.99,
    image: "/americhem-product-image.png",
    description: "Lysergamides",
    inStock: true,
    rating: 4.8,
    reviews: 100,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C20H16ClN5O2",
    casNumber: "1182367-47-0",
    detailedDescription:
      "High-quality research chemical for laboratory use only. This compound is intended for research purposes and should be handled by qualified professionals in appropriate laboratory settings.",
  },
  {
    id: 2,
    name: "1P-ETH-LAD 100μg Blotters",
    slug: "1p-eth-lad-100g-blotters",
    price: 248.99,
    image: "/americhem-product-image.png",
    description: "Lysergamides",
    inStock: true,
    rating: 4.6,
    reviews: 80,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C22H27N3O2",
    casNumber: "1906382-34-2",
    detailedDescription:
      "Premium research chemical compound designed for analytical and research applications. Requires proper laboratory equipment and trained personnel for handling.",
  },
  {
    id: 3,
    name: "2-FEA Pellets 60mg",
    slug: "2-fea-pellets-60mg",
    price: 12.99,
    image: "/americhem-product-image.png",
    description: "2-FEA",
    inStock: true,
    rating: 4.7,
    reviews: 95,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-54-9",
    detailedDescription:
      "Research-grade stimulant compound for scientific investigation. Each pellet contains precisely measured amounts for consistent research applications.",
  },
  {
    id: 4,
    name: "2/3-FEA Pellets 50mg/125mg",
    slug: "2-3-fea-pellets-50mg-125mg",
    price: 20.25,
    image: "/americhem-product-image.png",
    description: "3-FEA, 2-FEA",
    inStock: true,
    rating: 4.5,
    reviews: 120,
    category: "Stimulants",
    purity: "≥ 99%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C10H12FNO",
    casNumber: "1364933-55-0",
    detailedDescription:
      "Combination research compound featuring both 2-FEA and 3-FEA in precisely measured pellet form for comparative studies and research applications.",
  },
  {
    id: 5,
    name: "4-HO-MET 20mg Pellets",
    slug: "4-ho-met-20mg-pellets",
    price: 24,
    image: "/americhem-product-image.png",
    description: "4-HO-MET",
    inStock: true,
    rating: 4.6,
    reviews: 75,
    category: "Tryptamines",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C13H18N2O2",
    casNumber: "77872-41-4",
    detailedDescription:
      "High-purity tryptamine derivative for advanced research applications. Manufactured under strict quality control standards for consistent results.",
  },
  {
    id: 6,
    name: "Buy 1B-LSD 125mcg Blotters",
    slug: "buy-1b-lsd-125mcg-blotters",
    price: 30.99,
    image: "/americhem-product-image.png",
    description: "1B-LSD",
    inStock: true,
    rating: 4.4,
    reviews: 60,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O3",
    casNumber: "1445752-09-9",
    detailedDescription:
      "Research-grade lysergamide compound on high-quality blotter paper. Designed for analytical chemistry and research purposes only.",
  },
  {
    id: 7,
    name: "Buy 1cP-AL-LAD 150mcg Blotters",
    slug: "buy-1cp-al-lad-150mcg-blotters",
    price: 46.99,
    image: "/americhem-product-image.png",
    description: "1cP-AL-LAD, AL-LAD",
    inStock: true,
    rating: 4.3,
    reviews: 85,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C22H27N3O2",
    casNumber: "2349358-81-0",
    detailedDescription:
      "Advanced lysergamide research compound featuring enhanced stability and purity. Suitable for sophisticated analytical and research applications.",
  },
  {
    id: 8,
    name: "Buy 1cP-LSD 100mcg Blotters",
    slug: "buy-1cp-lsd-100mcg-blotters",
    price: 23.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.5,
    reviews: 70,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Premium quality research chemical on professional-grade blotter substrate. Manufactured to the highest standards for reliable research outcomes.",
  },
  {
    id: 9,
    name: "Buy 1cP-LSD 10mcg Micro Pellets",
    slug: "buy-1cp-lsd-10mcg-micro-pellets",
    price: 9.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.7,
    reviews: 45,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Micro-dosed research compound for precise analytical applications. Each pellet contains accurately measured amounts for consistent research protocols.",
  },
  {
    id: 10,
    name: "Buy 1cP-LSD 150mcg Art Blotters",
    slug: "buy-1cp-lsd-150mcg-art-blotters",
    price: 25.0,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.6,
    reviews: 90,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Premium art blotter featuring high-quality research compound. Designed for analytical chemistry with enhanced visual identification markers.",
  },
  {
    id: 11,
    name: "Buy 1cP-LSD 150mcg Pellets",
    slug: "buy-1cp-lsd-150mcg-pellets",
    price: 32.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.8,
    reviews: 65,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "High-concentration research pellets for advanced analytical studies. Manufactured under strict quality control for consistent research outcomes.",
  },
  {
    id: 12,
    name: "Buy 1cP-LSD 20mcg Micro Blotters",
    slug: "buy-1cp-lsd-20mcg-micro-blotters",
    price: 30.99,
    image: "/americhem-product-image.png",
    description: "1cP-LSD",
    inStock: true,
    rating: 4.5,
    reviews: 110,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "1906382-35-3",
    detailedDescription:
      "Micro-dosed blotter for precise research applications. Ideal for analytical chemistry requiring exact dosage measurements.",
  },
  {
    id: 13,
    name: "Buy 1cP-MiPLA 200mcg Blotters",
    slug: "buy-1cp-mipla-200mcg-blotters",
    price: 42.99,
    image: "/americhem-product-image.png",
    description: "1cP-MiPLA",
    inStock: true,
    rating: 4.4,
    reviews: 55,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C24H31N3O2",
    casNumber: "2349358-82-1",
    detailedDescription:
      "Advanced lysergamide research compound with unique structural properties. Suitable for sophisticated analytical and comparative studies.",
  },
  {
    id: 14,
    name: "Buy 1D-LSD 10mcg Micro Pellets",
    slug: "buy-1d-lsd-10mcg-micro-pellets",
    price: 13.25,
    image: "/americhem-product-image.png",
    description: "1D-LSD",
    inStock: true,
    rating: 4.7,
    reviews: 125,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C27H35N3O2",
    casNumber: "2349358-83-2",
    detailedDescription:
      "Next-generation lysergamide research compound in micro-pellet form. Designed for precision analytical applications and research protocols.",
  },
  {
    id: 15,
    name: "Buy 1D-LSD 150mcg Blotters",
    slug: "buy-1d-lsd-150mcg-blotters",
    price: 58.99,
    image: "/americhem-product-image.png",
    description: "1D-LSD",
    inStock: true,
    rating: 4.3,
    reviews: 40,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C27H35N3O2",
    casNumber: "2349358-83-2",
    detailedDescription:
      "Premium 1D-LSD research compound on high-quality blotter substrate. Features enhanced stability and purity for advanced research applications.",
  },
  {
    id: 16,
    name: "Buy 1D-LSD 225mcg Pellets",
    slug: "buy-1d-lsd-225mcg-pellets",
    price: 86.99,
    image: "/americhem-product-image.png",
    description: "1D-LSD",
    inStock: true,
    rating: 4.6,
    reviews: 80,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C27H35N3O2",
    casNumber: "2349358-83-2",
    detailedDescription:
      "High-concentration 1D-LSD pellets for advanced research applications. Manufactured to pharmaceutical standards for consistent analytical results.",
  },
  {
    id: 17,
    name: "Buy 1P-LSD 100mcg Blotters",
    slug: "buy-1p-lsd-100mcg-blotters",
    price: 24.0,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.5,
    reviews: 150,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "Classic 1P-LSD research compound on professional-grade blotter paper. Widely used in analytical chemistry and research applications.",
  },
  {
    id: 18,
    name: "Buy 1P-LSD 150mcg Art Blotters",
    slug: "buy-1p-lsd-150mcg-art-blotters",
    price: 25.99,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.4,
    reviews: 95,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "Artistic blotter design featuring high-quality 1P-LSD research compound. Combines aesthetic appeal with analytical precision.",
  },
  {
    id: 19,
    name: "Buy 1P-LSD 150mcg Pellets",
    slug: "buy-1p-lsd-150mcg-pellets",
    price: 32.99,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.6,
    reviews: 85,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Pellets",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "High-concentration 1P-LSD pellets for advanced research protocols. Features enhanced stability and precise dosage for analytical applications.",
  },
  {
    id: 20,
    name: "Buy 1P-LSD 20mcg Micro Blotters",
    slug: "buy-1p-lsd-20mcg-micro-blotters",
    price: 31.99,
    image: "/americhem-product-image.png",
    description: "1P-LSD",
    inStock: true,
    rating: 4.3,
    reviews: 70,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C23H29N3O2",
    casNumber: "2349358-84-3",
    detailedDescription:
      "Micro-dosed 1P-LSD blotters for precision research applications. Ideal for analytical studies requiring exact dosage control.",
  },
  {
    id: 21,
    name: "Buy 1V LSD 150mcg Blotters",
    slug: "buy-1v-lsd-150mcg-blotters",
    price: 39.0,
    image: "/americhem-product-image.png",
    description: "1V-LSD Valerie",
    inStock: true,
    rating: 4.5,
    reviews: 120,
    category: "Lysergamides",
    purity: "≥ 98%",
    form: "Blotter",
    storage: "Store in a cool, dry place away from direct sunlight",
    molecularFormula: "C25H31N3O3",
    casNumber: "2349358-85-4",
    detailedDescription:
      "1V-LSD (Valerie) research compound featuring unique structural modifications. Designed for comparative analytical studies and research applications.",
  },
]

// Generate slugs for any products that don't have one
export const productsWithSlugs = allProducts.map((product) => ({
  ...product,
  slug: product.slug || slugify(product.name),
}))
